module.exports = {
    CALCULATOR_APP: "CALCULATOR_APP",
    USER_CONNECTED: "USER_CONNECTED",
    CALCULATION_RECEIVED: "CALCULATION_RECEIVED",
    CALCULATOR_START : "CALCULATOR_START",
    CALCULATION_SENT: "CALCULATION_SENT",
    CALCULATOR : "CALCULATOR",
    VERIFY_USER: "VERIFY_USER",
};